Repository webpack-contrib/html-webpack-plugin, pull requests merged in 2018-02, with the labels that each got.

#4 chore(package): add `release` script
  package-lock.json
  package.json
  yarn.lock
Labels: semver: Patch, status: approved, type: Chore

#5 docs(LICENSE): use JSF license
  LICENSE
Labels: semver: Patch, status: Approved, type: Docs

#6 ci(.bithoundrc): rm bithound service
  .bithoundrc
Labels: semver: Patch, status: Approved, type: CI

#7 ci(.travis): add node `lts/*` && `stable`
  .travis.yml
  package.json
Labels: semver: Patch, type: CI

#14 fix(package): add `tapable >= v1.0.0` (`dependencies`)
  package-lock.json
  package.json
Labels: semver: Patch, status: Pending, type: Bug

#11 docs(README): standardize
  README.md
Labels: semver: Patch, status: Approved, type: Docs

#17 fix(package): remove unnecessary `prepare` script
  package.json
Labels: semver: Patch, status: Approved, type: Bug
